-- Insert sample trader profile (replace with an actual Supabase auth user ID)
-- You'll need to get an actual user ID from your Supabase auth users table
-- For testing, you can use a placeholder ID or create one first

-- First, let's see if there are existing profiles in the table
SELECT * FROM public.profiles LIMIT 5;

-- If there are no profiles, you'll need to register a user first
-- through your app, which should trigger the handle_new_user function

-- For now, let's create a sample profile for testing
-- Note: We're omitting created_at since it's auto-generated by the table
INSERT INTO public.profiles (
  id, 
  full_name, 
  phone, 
  location, 
  avatar_url, 
  role
) VALUES 
(
  -- Use a dummy UUID for now; you'll need to replace with real user ID
  '00000000-0000-0000-0000-000000000001',
  'Sample Trader',
  '+254712345678',
  'Nairobi',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=200&q=80',
  'trader'
)
ON CONFLICT (id) DO NOTHING;

-- Insert sample products 
INSERT INTO public.products (
  trader_id, 
  name, 
  description, 
  price, 
  category, 
  image_url, 
  stock_quantity, 
  rating
) VALUES 
(
  '00000000-0000-0000-0000-000000000001',
  'Nike Air Max 270',
  'A premium running shoe with maximum air cushioning for comfort and style. Perfect for daily wear and running activities.',
  12000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  50,
  4.5
),
(
  '00000000-0000-0000-0000-000000000001',
  'Adidas Ultraboost 22',
  'Energy-returning BOOST midsole for maximum comfort and responsiveness. Ideal for running and everyday activities.',
  15000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  30,
  4.7
),
(
  '00000000-0000-0000-0000-000000000001',
  'Puma RS-X Reinvention',
  'Bold and chunky design with premium materials for a statement look. Perfect for casual wear.',
  8000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1543508282-6319a3e2621f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  25,
  4.3
),
(
  '00000000-0000-0000-0000-000000000001',
  'New Balance 574 Core',
  'Classic silhouette with modern comfort technology and all-day support. Timeless design.',
  7500.00,
  'Footwear',
  'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb89e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  40,
  4.2
),
(
  '00000000-0000-0000-0000-000000000001',
  'Converse Chuck Taylor All Star',
  'Iconic canvas sneakers with timeless design and versatile style. Perfect for any outfit.',
  5000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1605408499393-6360c7281b90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  60,
  4.4
),
(
  '00000000-0000-0000-0000-000000000001',
  'Vans Old Skool Classic',
  'The original Vans high-top with signature side stripes. A timeless classic for skateboarders and casual wear.',
  4500.00,
  'Footwear',
  'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  35,
  4.6
),
(
  '00000000-0000-0000-0000-000000000001',
  'Jordan Retro 1',
  'The iconic basketball shoe that started it all. Premium materials and timeless design.',
  20000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  15,
  4.8
),
(
  '00000000-0000-0000-0000-000000000001',
  'Timberland Premium 6" Boots',
  'Durable and waterproof boots perfect for all seasons. Iconic style and excellent quality.',
  18000.00,
  'Footwear',
  'https://images.unsplash.com/photo-1549298916-b41d501d3772?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=500&q=80',
  20,
  4.5
);

-- Verify the insertions
SELECT * FROM public.products LIMIT 10;
SELECT * FROM public.profiles LIMIT 10;